site_name: Digital Controllers
site_description: Digital Controllers Documentation Hub - an open-source ATC/C2 documentation project by DCS controllers, for DCS controllers.
site_url: https://digital-controllers.com

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.path
    - content.tabs.link
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/logo.webp

nav:
  - Home: index.md
  - About:
      - Contributing: about/contributing.md
      - Publications: about/publications.md
  - Publications: about/publications.md
  - ATC Guide:
      - atc-guide/index.md
      - General Knowledge:
          - atc-guide/general-knowledge/index.md
          - Radiotelephony: atc-guide/general-knowledge/radiotelephony.md
          - Radio Theory: atc-guide/general-knowledge/radio_theory.md
          - Radar Theory: atc-guide/general-knowledge/radar_theory.md
          - Altimetry: atc-guide/general-knowledge/altimetry.md
          - Meteorology: atc-guide/general-knowledge/meteorology.md
          - Flight Rules: atc-guide/general-knowledge/flight_rules.md
          - ATC Positions: atc-guide/general-knowledge/positions.md
          - Airspace: atc-guide/general-knowledge/airspace.md
          - Flight Information Services: atc-guide/general-knowledge/fis.md
      - Ground Control:
          - atc-guide/ground/index.md
          - Flight Plan: atc-guide/ground/flight_plan.md
          - Departure Clearance: atc-guide/ground/departure_clearance.md
          - Taxi: atc-guide/ground/taxi.md
          - Traffic Management: atc-guide/ground/traffic_management.md
      - Tower Control:
          - atc-guide/tower/index.md
      - Approach Control:
          - atc-guide/approach/index.md
      - Enroute Control:
          - atc-guide/enroute/index.md
  - TAC C2 Guide:
      - tac-c2-guide/index.md
      - General Knowledge:
          - tac-c2-guide/general-knowledge/index.md
      - Identification Control:
          - tac-c2-guide/identification/index.md
      - Weapons Control:
          - tac-c2-guide/weapons/index.md
  - Pilot Guide:
      - pilot-guide/index.md
      - General Knowledge:
          - Squawk Codes: pilot-guide/general-knowledge/squawks.md
  - Bullseye Trainer:
      - bullseye-trainer/index.md
      - Guide: bullseye-trainer/guide.md
      - Trainer: bullseye-trainer/trainer.md
      - Calculator: bullseye-trainer/calculator.md
plugins:
  - search

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css
