site_name: Digital Controllers
site_description: Digital Controllers Documentation Hub - an open-source ATC documentation project by DCS controllers, for DCS controllers.
site_url: https://digital-controllers.com
theme:
  name: material
  features:
    - navigation.indexes
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/logo.png
nav:
  - Welcome: index.md
  - Contributing: contributing.md
  - General Knowledge:
    - general-knowledge/index.md
    - Radiotelephony: general-knowledge/radiotelephony.md
    - Radio Theory: general-knowledge/radio_theory.md
    - Radar Theory: general-knowledge/radar_theory.md
    - Altimetry: general-knowledge/altimetry.md
    - Meteorology: general-knowledge/meteorology.md
    - Flight Rules: general-knowledge/flight_rules.md
plugins:
  - social
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
